name: Build Push Sign
on: { push: { branches: ['main'] } }

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Login to GitHub
        uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: build+push
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: ghcr.io/junaid18183/sampleapp:latest

      - uses: sigstore/cosign-installer@main

      - name: Sign the images
        run: |
          cosign sign ghcr.io/junaid18183/sampleapp:latest
        env:
          COSIGN_EXPERIMENTAL: 1